storage:
  dbPath: /data/db
  engine: wiredTiger

systemLog:
  destination: file
  logAppend: true
  path: /data/db/mongod.log

net:
  port: 27017
  bindIp: 0.0.0.0

security:
  authorization: enabled

setParameter:
  enableLocalhostAuthBypass: false
